; Listing generated by Microsoft (R) Optimizing Compiler Version 19.21.27702.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\student.DESKTOP-L5S2T4S\AppData\Local\Temp\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
